name: Docker Build and Trivy Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  trivy_scan:
    runs-on: ubuntu-latest  # Utilisation d'Ubuntu sur GitHub Actions

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          docker build -t myimage .

      - name: Install Trivy
        run: |
          curl -sSfL https://github.com/aquasecurity/trivy/releases/download/v0.22.0/trivy_0.22.0_Linux-x86_64.tar.gz -o trivy.tar.gz
          tar -zxvf trivy.tar.gz
          sudo mv trivy /usr/local/bin/

      - name: Scan Docker image with Trivy
        run: |
          trivy image myimage

      - name: Fail if critical vulnerabilities found
        if: failure()
        run: |
          echo "Critical vulnerabilities found. Failing the build."
          exit 1

